version: '3.7'

services:
  app:
    environment:
      - FLASK_ENV=development
    volumes:
      - ./todolist:/app
    build: ./todolist
    container_name: 'todolist'
    ports:
      - "5001:5000"
    command: flask run --host=0.0.0.0

    depends_on:
     - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 't0d0l1st'
